### ISSUE TITLE
Allow users to supply entire quantum dots

### ISSUE THREAD

**Issue by BvB93** [nlesc-nano/nano-CAT#15]
Allow users to entire complete quantum dots rather than constructing them from cores and ligands.

Example of the (tentative) input syntax for the .yaml file:
```
input_qd:
    - 'QD_OCC.xyz'               # Ethoxide-based quantum dot
        ligand_smiles: '[O-]CC'  # A SMILES string of the ligand
        ligand_anchor: '[O-]C'   # A SMILES string of the ligand anchor group
        guess_bonds: True        # Guess bonds for all atoms within the ligand(s)

    - 'fancy_acetate_QD.pdb'     # Acetate-based quantum dot
        ligand_smiles: '[O-](O=)CC'
        ligand_anchor: '[O-]C'
```
